# Site settings
baseurl = "https://dataton2023.plataformadigitalnacional.org/"
relativeURLs = true
languageCode = "es-mx"
defaultContentLanguage = "es"
title = "Datatón Anticorrupción"
theme = "dataton-agency"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines
  name = "Datatón Anticorrupción 2023"
  description = """El datatón anticorrupción es una iniciativa donde construiremos herramientas 
  que analicen datos abiertos con el fin de combatir la corrupción en México."""
  twitter_user = "@SESNAOficial"
  images = ["/img/card-2023.jpg"]
  start_date = "2023-11-30T17:00-06:00"
  end_date = "2023-12-03T16:00-06:00"
  logo = "/img/logo-navbar.svg"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "/favicon.ico"

  # 404 error customization
  [params.error404]
    heading = "No se encontró esa página"
    text = "Por favor visita [esta página](/)"

  # Navigation
  [params.navigation]
    brand = "Datatón Anticorrupción"
    # Optional logo as brand stored in img/
    logo = "logo-navbar.svg"
 
    [[menu.main]]
      name = "Convocatoria"
      url = "/#info"
      weight = 1

    [[menu.main]]
      name = "Bases"
      url = "/files/DatatonAnticorrupcion2023-Basesv1_1.pdf"
      weight = 4

    [[menu.main]]
      url = "/preguntas-frecuentes"
      name = "Dudas"
      weight = 9

  [params.navigation_button]
    link = "/participa"
    label = "Participa"      

  # Sección de hero en homepage. 
  [params.hero]
  # Dado que el layout es muy particular para este evento, el contenido está 
  # hardcoded en layouts/partials/hero.html

  # Sección de información clave
  [params.info]
    enable = true

  [params.faq]
    enable = true

  # Mentores
  [params.mentores]
    enable = false

  # Jueces
  [params.jueces]
    enable = true

  # Sponsors section
  # Los logos de los aliados están en 'static/img/logos'.
  # El tamaño ideal es 280px*80px
    [params.sponsors]
      enable = true
      center = true

    [params.sponsors1_list]
      enable = false
      title = "Patrocinado por"

      [[params.sponsors1]]
        logo = "sre-amexcid.png"
        link = "https://www.gob.mx/amexcid"

      [[params.sponsors1]]
        logo = "cooperacion-giz.jpg"
        link = "https://www.giz.de/en/worldwide/33041.html"

    [params.sponsors2_list]
      
      enable = true
      title = "Una iniciativa de " 

      [[params.sponsors2]]
        logo = "sna.png"
        link = "https://www.sna.org.mx/"

      [[params.sponsors2]]
        logo = "sesna.png"
        link = "https://www.gob.mx/sesna"

    [params.sponsors3_list]
      enable = false
      title = "Partners" 

      [[params.sponsors3]]
        logo = "platzi.jpg"
        link = "https://platzi.com/escuela/escuela-datos"

      [[params.sponsors3]]
        logo = "del.png"
        link = "https://beacons.ai/dataengineeringlatam"

      [[params.sponsors3]]
        logo = "ST_logo_C.png"
        link = "https://socialtic.org/"

    [params.sponsors4_list]
      enable = true
      title = "Producido por"

      [[params.sponsors4]]
        logo = "sg.png"
        link = "https://sg.com.mx"

      
  # Footer section
  [params.footer]
    enable = true
    leyenda = ""
    copyright = "Otro fantástico evento de <a href='https://sg.com.mx'>SG</a>."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/SESNAOficial"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/SESNAOficial"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-envelope-o"
      link = "mailto:dataton@sg.com.mx"
      title = "Correo electrónico"

    [[params.footer.quicklinks]]
      text = "Código de Conducta"
      link = "/coc"

    [[params.footer.quicklinks]]
      text = "Privacidad de datos"
      link = "/files/DatatonAnticorrupcion2023-AvisoDePrivacidadv1_1.pdf"

